author = "HungTran"
description = "Hung Tran Duy's resume"

primaryColor = "#5e81ac"
textPrimaryColor = "#292929"

[floatingbutton]
    enable = true
    downloadButton = true

[profile]
    enable = true
    name = "Hung Tran Duy"
    tagline = "Backend Software Engineer"
    avatar = "avatar.png"

[contact]
    enable = true
    location = "Vietnam"

    [[contact.list]]
    icon = "fas fa-phone-square"
    url = "tel:#"
    text = "0123456789"
    [[contact.list]]
    icon = "fas fa-envelope-square"
    url = "mailto:#"
    text = "example@gmail.com"
    [[contact.list]]
    icon = "fas fa-globe"
    url = "#"
    text = "www.example.com"

[skills]
    enable = true

    [[skills.list]]
    title = "Technical"
    [[skills.list.items]]
    details = "JavaScript/Angular/React/Vue"
    [[skills.list.items]]
    details = "Python/Ruby/PHP"
    [[skills.list.items]]
    details = "Node.js/ASP.NET"
    [[skills.list.items]]
    details = "PostgreSQL/MySQL"
    [[skills.list.items]]
    details = "Object-oriented design"
    [[skills.list.items]]
    details = "Design and implement database structures"
    [[skills.list.items]]
    details = "Lead and deliver complex software systems"

    [[skills.list]]
    title = "Professional"
    [[skills.list.items]]
    details = "Effective communication"
    [[skills.list.items]]
    details = "Team player"
    [[skills.list.items]]
    details = "Strong problem solver"
    [[skills.list.items]]
    details = "Good time management"

[education]
    enable = true

    [[education.list]]
    degree = "MSc in Computer Science"
    university = "University College London"
    dates = "2010 - 2011"
    [[education.list]]
    degree = "BSc Maths and Physics"
    university = "Imperial College London"
    dates = "2007 - 2010"

[awards]
    enable = true

    [[awards.list]]
    name = "Award Lorem Ipsum"
    body = "Microsoft lorem ipsum"
    date = "2019"
    [[awards.list]]
    name = "Award Donec Sodales"
    body = "Oracle Aenean"
    date = "2017"

[languages]
    enable = true

    [[languages.list]]
    name = "English"
    level = "Native"
    [[languages.list]]
    name = "Spanish"
    level = "Professional"

[interests]
    enable = true

    [[interests.list]]
    name = "Climbing"
    [[interests.list]]
    name = "Snowboarding"
    [[interests.list]]
    name = "Photography"
    [[interests.list]]
    name = "Travelling"

[summary]
    enable = true
    text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

[experience]
    enable = true

    [[experience.list]]
    title = "Senior Software Engineer"
    dates = "2019 - Present"
    company = "Google"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
    [[experience.list.items]]
    details = "Lorem ipsum dolor sit amet, consectetuer."
    [[experience.list.items]]
    details = "Aenean commodo ligula eget dolor."
    [[experience.list.items]]
    details = "Etiam ultricies nisi vel augue."

    [[experience.list]]
    title = "Lead Software Developer"
    dates = "2016 - 2019"
    company = "Apple"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
    [[experience.list.items]]
    details = "Lorem ipsum dolor sit amet, consectetuer."
    [[experience.list.items]]
    details = "Aenean commodo ligula eget dolor."

    [[experience.list]]
    title = "Senior Software Developer"
    dates = "2014 - 2016"
    company = "Dropbox"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [[experience.list]]
    title = "Senior Developer"
    dates = "2013 - 2014"
    company = "Uber"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

    [[experience.list]]
    title = "Backend Developer"
    dates = "2014 - 2016"
    company = "Amazon"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [[experience.list]]
    title = "Frontend Developer"
    dates = "2013 - 2014"
    company = "Startup"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

[projects]
    enable = true

    [[projects.list]]
    title = "Project Lorem Ipsum"
    meta = "Open Source"
    tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [[projects.list]]
    title = "Project Sed Fringilla"
    meta = "Open Source"
    tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [[projects.list]]
    title = "Project Praesent"
    meta = "Open Source"
    tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

[information]
    enable = true

    [[information.list]]
    title = "Papers"
    [[information.list.items]]
    details = "2018 · Lorem Ipsum"
    [[information.list.items]]
    details = "2016 · Sed Fringilla"

    [[information.list]]
    title = "Interests"
    details = "Climbing, Snowboarding, Photography, Travelling"

[social]
    enable = true

    [[social.list]]
    icon = "fab fa-github-square"
    url = "//github.com/username"
    title = "username"
    [[social.list]]
    icon = "fab fa-linkedin"
    url = "//linkedin.com/in/username"
    title = "username"
    [[social.list]]
    icon = "fab fa-twitter-square"
    url = "//twitter.com/username"
    title = "@username"

